spring:
  application:
    name: auth
  datasource:
    username: root
    password: mysqlpassword
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.1.20:3306/auth?useUnicode=true&characterEncoding=utf-8
    hikari:
      auto-commit: true
      connection-init-sql: SET NAMES utf8mb4
      pool-name: auth-hi
  redis:
    database: 0 #redis索引
    host: 172.16.1.20
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大数量
        max-wait: -1 # 连接池最大阻塞时间
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
    timeout: 2000
  flyway:
    locations: classpath:db/migration
    url: jdbc:mysql://172.16.1.20:3306/mysql
    user: root
    password: mysqlpassword
    schemas: auth
server:
  port: 9000

mybatis:
  mapper-locations: classpath:mybatis/*.xml